name: Build and deploy a preview website

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: "./built-website"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./built-website"
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
            source-dir: ./built-website
            preview-branch: gh-pages
            umbrella-dir: chapter/pr-preview
            pages-base-path: chapter
            qr-code: true